### ISSUE TITLE
How can I push docker image to Docker Hub?

### ISSUE THREAD

**Issue by ShotaOchi** [smaakage85/dockr#1]
Hi,
Thanks for your great work.
I'm studying dockr package now.
I have a question.

How can I push docker image to Docker Hub by using the functions of dockr?
I can automate publishing of my docker image if I can push docker image to Docker Hub seamlessly.

Thanks,
Shota

**Comment by smaakage85** [comment]
Hi Shota

First of all: Thank you and thank you for the feedback. 

Sorry for the late answer, I first became aware of your issue yesterday.

Publishing the Docker Image is not something, that I have developed any functions for as is. But it is certainly something, that could be interesting to include in the package. Do you have a good idea of the designs of an implementation? If so, you are very welcome to make a pull request.

As of right now I am trying my best to actually releasing the package on CRAN.

Best, Lars

**Comment by smaakage85** [comment]
Hi @ShotaOchi 

Any comments? Please write me. Until then, I will close the issue.
